export const SahayatriTheme = {
  colors: {
    surface: '#f9f9ff',
    surfaceDim: '#cfdaf2',
    surfaceBright: '#f9f9ff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f0f3ff',
    surfaceContainer: '#e7eeff',
    surfaceContainerHigh: '#dee8ff',
    surfaceContainerHighest: '#d8e3fb',
    onSurface: '#111c2d',
    onSurfaceVariant: '#3f4944',
    inverseSurface: '#263143',
    inverseOnSurface: '#ecf1ff',
    outline: '#6f7973',
    outlineVariant: '#bec9c2',
    surfaceTint: '#1b6b51',
    primary: '#004532',
    onPrimary: '#ffffff',
    primaryContainer: '#065f46',
    onPrimaryContainer: '#8bd6b7',
    inversePrimary: '#8bd6b6',
    secondary: '#904d00',
    onSecondary: '#ffffff',
    secondaryContainer: '#fe932c',
    onSecondaryContainer: '#663500',
    tertiary: '#00415f',
    onTertiary: '#ffffff',
    tertiaryContainer: '#005980',
    onTertiaryContainer: '#8bcfff',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#a6f2d1',
    primaryFixedDim: '#8bd6b6',
    onPrimaryFixed: '#002116',
    onPrimaryFixedVariant: '#00513b',
    secondaryFixed: '#ffdcc3',
    secondaryFixedDim: '#ffb77d',
    onSecondaryFixed: '#2f1500',
    onSecondaryFixedVariant: '#6e3900',
    tertiaryFixed: '#c9e6ff',
    tertiaryFixedDim: '#89ceff',
    onTertiaryFixed: '#001e2f',
    onTertiaryFixedVariant: '#004c6e',
    background: '#f9f9ff',
    onBackground: '#111c2d',
    surfaceVariant: '#d8e3fb',
  },
  typography: {
    displayLg: {
      fontSize: 32,
      fontWeight: '700',
      lineHeight: 40,
    },
    headlineMd: {
      fontSize: 24,
      fontWeight: '600',
      lineHeight: 32,
    },
    headlineSm: {
      fontSize: 20,
      fontWeight: '600',
      lineHeight: 28,
    },
    bodyLg: {
      fontSize: 18,
      fontWeight: '400',
      lineHeight: 28,
    },
    bodyMd: {
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 24,
    },
    bodySm: {
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 20,
    },
    labelMd: {
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 16,
    },
    headlineLgMobile: {
      fontSize: 28,
      fontWeight: '700',
      lineHeight: 36,
    },
  },
  spacing: {
    base: 4,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    gutter: 16,
    marginMobile: 16,
    marginDesktop: 32,
  },
  radius: {
    sm: 4,
    default: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
} as const;
